### ISSUE TITLE
server: issue on genereting hub types with tapper

### ISSUE THREAD

**Issue by vkuprin** [ligomoku/gomoku#291]
```bash
yarn codegen-run:server
yarn run v1.22.22
$ dotnet tsrts --project ./GomokuServer/src/GomokuServer.Api/GomokuServer.Api.csproj --output ./GomokuClient/packages/gomoku-api/hubs --asm && yarn format
Start loading the csproj of /Users/kuprins/Desktop/Coding/gomoku/gomoku/GomokuServer/src/GomokuServer.Api/GomokuServer.Api.csproj.
Create Compilation...
Add Header...
Transpile GomokuServer.Api.Hubs.Messages.Client.ApproveRematchMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.ApproveUndoMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.GetClockMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.KeepAliveMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.MakeMoveClientMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.ReceiveInvitationToPlayMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.RematchRequestMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.RequestUndoMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.ResignClientMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.ChatMessageClientMessage...
Transpile GomokuServer.Api.Hubs.Messages.Client.SendInvitationToPlayMessage...
Add Header...
Transpile GomokuServer.Api.Hubs.Messages.Server.BothPlayersJoinedMessage...
GomokuServer.Api.Hubs.Messages.Server.BothPlayersJoinedMessage can not be transpiled.
======== Exception ========
System.InvalidOperationException: GomokuServer.Application.Games.Dto.PlayersDto is not supported.
   at Tapper.DefaultTypeMapperProvider.GetTypeMapper(ITypeSymbol type)
   at Tapper.TypeMappers.TypeMapper.MapTo(ITypeSymbol typeSymbol, ITranspilationOptions options)
   at Tapper.TypeTranslators.DefaultMessageTypeTranslator.Translate(CodeWriter& codeWriter, INamedTypeSymbol typeSymbol, ITranspilationOptions options)
   at Tapper.TypeScriptCodeGenerator.AddType(INamedTypeSymbol typeSymbol, CodeWriter& writer)
   at Tapper.Transpiler.Transpile()
   at TypedSignalR.Client.TypeScript.App.TranspileCore(Compilation compilation, String outputDir, NewLineOption newLine, Int32 indent, Boolean referencedAssembliesTranspilation, SerializerOption serializerOption, NamingStyle namingStyle, EnumStyle enumStyle, MethodStyle methodStyle, Boolean enableAttributeReference) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 133
   at TypedSignalR.Client.TypeScript.App.Transpile(String project, String output, NewLineOption newLine, Boolean assemblies, SerializerOption serializer, NamingStyle namingStyle, EnumStyle enum, MethodStyle method, Boolean attribute) in /home/runner/work/TypedSignalR.Client.TypeScript/TypedSignalR.Client.TypeScript/src/TypedSignalR.Client.TypeScript.Generator/App.cs:line 55

```

**Comment by vkuprin** [comment]
FYI, @Alequez97
